# https://about.codecov.io/blog/python-code-coverage-using-github-actions-and-codecov/
# https://docs.codecov.com/docs/codecovyml-reference

# https://docs.codecov.com/docs/ignoring-paths
ignore:
  - "demo"

