# prospector python tool configuration file

output-format: pylint
max-line-length: 120
#strictness: veryhigh
doc-warnings: true
member-warnings: true
auto-detect: false  # do not try to detect library used
test-warnings: true  # raise warnings in unit test folders

ignore-paths:
  - docs
  - demo

bandit:
  run: true
  options:
    config: .bandit.yaml
    #profile: xxx
    #severity: xxx
    #confidence: xxx

pylint:
  run: true
  disable:
    - missing-function-docstring
    - consider-using-f-string

dodgy:
  run: true

frosted:
  run: true

mccabe:
  run: true
  options:
    max-complexity: 10

mypy:
  run: false

pydocstyle:  # pep257 was renamed pydocstyle
  run: true
  options:
    convention: pep257
  disable:
    # D203 & D211 are mutually exclusive
    # 1 blank line required before class docstring
    - D203

    # D212 & D213 are mutually exclusive
    # Ref: http://www.pydocstyle.org/en/5.0.2/error_codes.html
    - D213
  enable:
    - D203
    - D212

pycodestyle:  #  pep8 was renamed pycodestyle
  run: true

pyflakes:
  run: true

pyroma:
  run: false

vulture:
  run: false

