ignore-paths:
  - docs
  - demo

test-warnings: true

bandit:
  # run it natively
  run: true
  options:
    skips:
      # Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
      - B101

pylint:
  run: true

dodgy:
  run: true

frosted:
  run: true

mccabe:
  run: true

mypy:
  run: true

pep257:
  run: true
  disable:
    # D203 & D211 are mutually exclusive
    # 1 blank line required before class docstring
    - D203

    # D212 & D213 are mutually exclusive
    # Ref: http://www.pydocstyle.org/en/5.0.2/error_codes.html
    - D213

pep8:
  run: true

pydocstyle:
  run: true

pycodestyle:
  run: true
  options:
    max-line-length: 127  # The GitHub editor is 127 chars wide

pyflakes:
  run: true

pyroma:
  run: false

vulture:
  run: false

