bandit:
  # run it natively
  run: true

pylint:
  run: true

dodgy:
  run: true

frosted:
  run: true

mccabe:
  run: true

mypy:
  run: true

pep257:
  run: true
  disable:
    # D203 & D211 are mutually exclusive
    # 1 blank line required before class docstring
    - D203

    # D212 & D213 are mutually exclusive
    # Ref: http://www.pydocstyle.org/en/5.0.2/error_codes.html
    - D213

pep8:
  run: true

pydocstyle:
  run: true

pyflakes:
  run: true

pyroma:
  run: true

vulture:
  run: true

