# Travis CI config file

os: linux
dist: bionic
language: python

# Version
python:
  - "2.7"
#  - "3.4"
#  - "3.5"
  - "3.6"      # current default Python on Travis CI
#  - "3.7"
#  - "3.8"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

# Command to install python dependencies
install:
  - pip install -r requirements.txt

# Initial setup script to download a minimal stock database that will be used for testing
before_script: |
  mkdir -p stock_db/test &&
  mkdir -p stock_db/empty &&
  mkdir -p stock_db/empty2 &&
  mkdir -p stock_db/empty3 &&
  mkdir -p stock_db/empty4 &&
  python get_yahoo_finance_data.py --concurrent 1 --file stock_db/test.txt --dir ./stock_db/test --startdate 20100101 --verbose

# Command to run the tests
script:
  #- pytest -v  # no coverage
  - coverage run -m pytest -v  # with coverage

after_success:
  # submit coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash)
  # submit coverage to coveralls.io
  - coveralls

